// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/realtime.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientEvent represents events sent from client to server
type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_Ping
	//	*ClientEvent_Typing
	//	*ClientEvent_ReadReceipt
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_proto_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientEvent) GetTyping() *TypingIndicator {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *ClientEvent) GetReadReceipt() *ReadReceipt {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ClientEvent_Typing struct {
	Typing *TypingIndicator `protobuf:"bytes,2,opt,name=typing,proto3,oneof"`
}

type ClientEvent_ReadReceipt struct {
	ReadReceipt *ReadReceipt `protobuf:"bytes,3,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

func (*ClientEvent_Ping) isClientEvent_Event() {}

func (*ClientEvent_Typing) isClientEvent_Event() {}

func (*ClientEvent_ReadReceipt) isClientEvent_Event() {}

// ServerEvent represents events sent from server to client
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Pong
	//	*ServerEvent_NewMessage
	//	*ServerEvent_Typing
	//	*ServerEvent_Presence
	//	*ServerEvent_Delivered
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_proto_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerEvent) GetNewMessage() *NewMessage {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *ServerEvent) GetTyping() *TypingIndicator {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *ServerEvent) GetPresence() *PresenceUpdate {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *ServerEvent) GetDelivered() *MessageDelivered {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Delivered); ok {
			return x.Delivered
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Pong struct {
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type ServerEvent_NewMessage struct {
	NewMessage *NewMessage `protobuf:"bytes,2,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type ServerEvent_Typing struct {
	Typing *TypingIndicator `protobuf:"bytes,3,opt,name=typing,proto3,oneof"`
}

type ServerEvent_Presence struct {
	Presence *PresenceUpdate `protobuf:"bytes,4,opt,name=presence,proto3,oneof"`
}

type ServerEvent_Delivered struct {
	Delivered *MessageDelivered `protobuf:"bytes,5,opt,name=delivered,proto3,oneof"`
}

func (*ServerEvent_Pong) isServerEvent_Event() {}

func (*ServerEvent_NewMessage) isServerEvent_Event() {}

func (*ServerEvent_Typing) isServerEvent_Event() {}

func (*ServerEvent_Presence) isServerEvent_Event() {}

func (*ServerEvent_Delivered) isServerEvent_Event() {}

// Ping for keep-alive
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Pong response
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// NewMessage pushed to client when a message arrives
type NewMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrl       string                 `protobuf:"bytes,5,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType      string                 `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewMessage) Reset() {
	*x = NewMessage{}
	mi := &file_proto_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessage) ProtoMessage() {}

func (x *NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessage.ProtoReflect.Descriptor instead.
func (*NewMessage) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{4}
}

func (x *NewMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NewMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *NewMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *NewMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewMessage) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *NewMessage) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *NewMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// TypingIndicator shows when someone is typing
type TypingIndicator struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTyping       bool                   `protobuf:"varint,3,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingIndicator) Reset() {
	*x = TypingIndicator{}
	mi := &file_proto_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingIndicator) ProtoMessage() {}

func (x *TypingIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingIndicator.ProtoReflect.Descriptor instead.
func (*TypingIndicator) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{5}
}

func (x *TypingIndicator) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingIndicator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingIndicator) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

// PresenceUpdate shows online/offline status
type PresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "online", "offline", "away"
	LastSeen      string                 `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_proto_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{6}
}

func (x *PresenceUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PresenceUpdate) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

// MessageDelivered confirms message delivery
type MessageDelivered struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageDelivered) Reset() {
	*x = MessageDelivered{}
	mi := &file_proto_realtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelivered) ProtoMessage() {}

func (x *MessageDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelivered.ProtoReflect.Descriptor instead.
func (*MessageDelivered) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{7}
}

func (x *MessageDelivered) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDelivered) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// ReadReceipt sent by client when they read messages
type ReadReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadReceipt) Reset() {
	*x = ReadReceipt{}
	mi := &file_proto_realtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceipt) ProtoMessage() {}

func (x *ReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceipt.ProtoReflect.Descriptor instead.
func (*ReadReceipt) Descriptor() ([]byte, []int) {
	return file_proto_realtime_proto_rawDescGZIP(), []int{8}
}

func (x *ReadReceipt) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_proto_realtime_proto protoreflect.FileDescriptor

const file_proto_realtime_proto_rawDesc = "" +
	"\n" +
	"\x14proto/realtime.proto\x12\x05proto\"\xa4\x01\n" +
	"\vClientEvent\x12!\n" +
	"\x04ping\x18\x01 \x01(\v2\v.proto.PingH\x00R\x04ping\x120\n" +
	"\x06typing\x18\x02 \x01(\v2\x16.proto.TypingIndicatorH\x00R\x06typing\x127\n" +
	"\fread_receipt\x18\x03 \x01(\v2\x12.proto.ReadReceiptH\x00R\vreadReceiptB\a\n" +
	"\x05event\"\x8f\x02\n" +
	"\vServerEvent\x12!\n" +
	"\x04pong\x18\x01 \x01(\v2\v.proto.PongH\x00R\x04pong\x124\n" +
	"\vnew_message\x18\x02 \x01(\v2\x11.proto.NewMessageH\x00R\n" +
	"newMessage\x120\n" +
	"\x06typing\x18\x03 \x01(\v2\x16.proto.TypingIndicatorH\x00R\x06typing\x123\n" +
	"\bpresence\x18\x04 \x01(\v2\x15.proto.PresenceUpdateH\x00R\bpresence\x127\n" +
	"\tdelivered\x18\x05 \x01(\v2\x17.proto.MessageDeliveredH\x00R\tdeliveredB\a\n" +
	"\x05event\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xe6\x01\n" +
	"\n" +
	"NewMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\x05 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"p\n" +
	"\x0fTypingIndicator\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_typing\x18\x03 \x01(\bR\bisTyping\"^\n" +
	"\x0ePresenceUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\tR\blastSeen\"Z\n" +
	"\x10MessageDelivered\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"U\n" +
	"\vReadReceipt\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId2H\n" +
	"\x0fRealtimeService\x125\n" +
	"\aConnect\x12\x12.proto.ClientEvent\x1a\x12.proto.ServerEvent(\x010\x01B'Z%github.com/dykethecreator/GoApp/protob\x06proto3"

var (
	file_proto_realtime_proto_rawDescOnce sync.Once
	file_proto_realtime_proto_rawDescData []byte
)

func file_proto_realtime_proto_rawDescGZIP() []byte {
	file_proto_realtime_proto_rawDescOnce.Do(func() {
		file_proto_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realtime_proto_rawDesc), len(file_proto_realtime_proto_rawDesc)))
	})
	return file_proto_realtime_proto_rawDescData
}

var file_proto_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_realtime_proto_goTypes = []any{
	(*ClientEvent)(nil),      // 0: proto.ClientEvent
	(*ServerEvent)(nil),      // 1: proto.ServerEvent
	(*Ping)(nil),             // 2: proto.Ping
	(*Pong)(nil),             // 3: proto.Pong
	(*NewMessage)(nil),       // 4: proto.NewMessage
	(*TypingIndicator)(nil),  // 5: proto.TypingIndicator
	(*PresenceUpdate)(nil),   // 6: proto.PresenceUpdate
	(*MessageDelivered)(nil), // 7: proto.MessageDelivered
	(*ReadReceipt)(nil),      // 8: proto.ReadReceipt
}
var file_proto_realtime_proto_depIdxs = []int32{
	2, // 0: proto.ClientEvent.ping:type_name -> proto.Ping
	5, // 1: proto.ClientEvent.typing:type_name -> proto.TypingIndicator
	8, // 2: proto.ClientEvent.read_receipt:type_name -> proto.ReadReceipt
	3, // 3: proto.ServerEvent.pong:type_name -> proto.Pong
	4, // 4: proto.ServerEvent.new_message:type_name -> proto.NewMessage
	5, // 5: proto.ServerEvent.typing:type_name -> proto.TypingIndicator
	6, // 6: proto.ServerEvent.presence:type_name -> proto.PresenceUpdate
	7, // 7: proto.ServerEvent.delivered:type_name -> proto.MessageDelivered
	0, // 8: proto.RealtimeService.Connect:input_type -> proto.ClientEvent
	1, // 9: proto.RealtimeService.Connect:output_type -> proto.ServerEvent
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_realtime_proto_init() }
func file_proto_realtime_proto_init() {
	if File_proto_realtime_proto != nil {
		return
	}
	file_proto_realtime_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_Ping)(nil),
		(*ClientEvent_Typing)(nil),
		(*ClientEvent_ReadReceipt)(nil),
	}
	file_proto_realtime_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerEvent_Pong)(nil),
		(*ServerEvent_NewMessage)(nil),
		(*ServerEvent_Typing)(nil),
		(*ServerEvent_Presence)(nil),
		(*ServerEvent_Delivered)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realtime_proto_rawDesc), len(file_proto_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realtime_proto_goTypes,
		DependencyIndexes: file_proto_realtime_proto_depIdxs,
		MessageInfos:      file_proto_realtime_proto_msgTypes,
	}.Build()
	File_proto_realtime_proto = out.File
	file_proto_realtime_proto_goTypes = nil
	file_proto_realtime_proto_depIdxs = nil
}
